import "./App.css";
import { useState, useEffect } from "react";
import { SentimentResults } from "./types/sentimentresult";
import {
  ChartBarIcon,
  ExclamationCircleIcon,
  CheckCircleIcon,
  FaceSmileIcon,
  FaceFrownIcon,
} from "@heroicons/react/24/outline";
import { getYoutubeSentiment } from "./services/youtubeanalysis.service";
import { getYoutubeDetails } from "./services/youtubedetails.service";
import Navbar from "./components/Navbar";
import Loader from "./components/Loader";
import Barchart from "./components/visualizations/Barchart";
import Linechart from "./components/visualizations/Linechart";
import Choroplethmap from "./components/visualizations/Choroplethmap";

function isValidYoutubeVideo(url: string) {
  const youtubeUrlPattern =
    /^(?:https?:\/\/)?(?:www\.)?(?:youtube\.com|youtu\.be)\/(?:watch\?v=|embed\/)?([a-zA-Z0-9_-]{11})/;
  return youtubeUrlPattern.test(url);
}

function App() {
  const [valid, setValid] = useState<boolean>(true);
  const [sentimentResults, setSentimentResults] = useState<SentimentResults>(
    []
  );
  const [currentTab, setCurrentTab] = useState<string | undefined>("");
  const [loading, setLoading] = useState<Boolean>(false);
  const [avgSentiment, setAvgSentiment] = useState(0);
  const [theme, setTheme] = useState("dark");
  const [analysed, setAnalysed] = useState(false);
  const [videoDetails, setVideoDetails] = useState<any>({});

  useEffect(() => {
    chrome.tabs.query({ active: true, currentWindow: true }, async (tabs) => {
      const currentUrl = tabs[0].url;
      setCurrentTab(currentUrl);
      if (currentUrl) {
        if (isValidYoutubeVideo(currentUrl)) {
          setValid(true);
          const videoId = getVideoId(currentTab!);
          if (videoId) {
            const videoDetails = await getYoutubeDetails({ videoId: videoId });
            setVideoDetails(videoDetails);
          }
        } else {
          setValid(false);
        }
      }
    });
  }, []);

  const handleClick = async () => {
    const videoId = getVideoId(currentTab!);
    if (videoId) {
      setAnalysed(true);
      setLoading(true);
      const sentimentResults = await getYoutubeSentiment({ videoId: videoId });
      // const sentimentResults = [
      //   {
      //     text: "In every “AI learns to walk” video I’ve seen, the AI either learns to walk in a weird, non-human way, or they use motion capture of a real person walking and simply train the AI to imitate that. I thought it was weird that nobody tried to train it to walk properly from scratch (without any external data), so I wanted to give it a shot! That’s what I said 4 months ago. It’s been really difficult, but I’ve finally managed to do it, so please watch the whole video! The final result ended up being awesome :)\r\n\r\nNOTE: From the last video, you guys made it clear you didn’t like that Albert had his brain reset, so from now his brain is here to stay (hopefully)! The next video I make with Albert will start with the brain we trained in this video, so with every video Albert will become more and more capable until he eventually learns to break out of my computer and take over the world. You also can only see one Albert, but there are actually 200 copies of Albert and the room he’s in training behind the camera to speed up the training.\r\n\r\nIf you want to learn more about how Albert actually works, you can read the rest of this very long comment I wrote explaining exactly how I trained him! (and please let the video play in the background while reading so YouTube will show Albert to more people)\r\n\r\n\nTHE BASICS\r\nI created everything using Unity and ML-Agents. Albert is controlled entirely by an artificial brain (neural network) which has 5 layers, the first layer consists of the inputs (the information Albert is given before taking action, like his limb positions and velocities), the last layer tells him what actions to take and the middle 3 layers, called hidden layers, are where the calculations are performed to convert the inputs into actions. His brain was trained using the standard algorithm in reinforcement learning; proximal policy optimization (PPO).\r\n\r\nFor each of Albert’s limbs I’ve given him (as an input) the position, velocity, angular velocity, contacts (if it’s touching the ground, wall or obstacle) and the strength applied to it. I’ve also given him the distance from each foot to the ground, direction of the closest target, the direction his body’s moving, his body’s velocity, the distance from his chest to his feet and the amount of time one foot has been in front of the other. As for his actions, we allow Albert to control each body part’s rotation and strength (with some limitations so his arm can’t bend backwards, for example).\r\n\r\nJust like the last videos, Albert was trained using reinforcement learning. For each of Albert's attempts, we calculate a score for how 'good' it was and make small, calculated adjustments to his brain to try to encourage the behaviors that led to a higher score and avoid those that led to a lower score. You can think of increasing Albert’s score as rewarding him and decreasing his score as punishing him, or you can think about it like natural selection where the best performing Alberts are most likely to reproduce. For this video there are 13 different types of rewards (ways to calculate Albert's score), we start off with only a couple and with each new room add more, always in an attempt to get him to walk.\r\n\r\n\nREWARD FUNCTION\r\nRoom 1: We start off very simple in the first room, we reward him based on how much he moved to the target and we punish him for moving in the wrong direction. This led to Albert doing the worm towards the target, since he figured out that was the easiest way for him to move the quickest/get the highest score. It would have been possible to get Albert to walk in a janky way by just rewarding him for moving towards the target and also punish him for falling as a team at Google (DeepMind) showed in 2017, but I thought it would make for a more enjoyable video if he starts off with the worm and over time learns to use his legs, rather than immediately being able to partially walk.\r\n\r\nRoom 2: In the second room we start checking if his limbs hit the ground. If the limb that hits the ground is a foot we reward him (but only if it's in front of his other foot, more on that later), if it isn’t, we punish him. I also made it so Albert wasn’t rewarded at all unless his chest was high enough to force it to at least be partially standing. As seen in the video, this encourages him to not fall over and encourages him to use his feet to do it. We also introduced a new reward designed to encourage smoother movement; if he approaches the maximum strength allowed on a limb he's punished, and he's rewarded if he uses a strength of almost 0. This encourages him to opt for the more human-like movement of using a bit of strength from many limbs as opposed to a lot of strength from one limb.\r\n\r\nRoom 3: This is where we start to polish Albert’s gait that developed in room 2 and teach him to turn. From here on we start using the chest height calculation as another direct reward where the higher his chest is the more he’s rewarded in an attempt to get him to stand up as straight as possible. These rewards so far give Albert a decent gait, however he’s still not using both of his feet (which was by far the hardest part of this project), so room 4 is designed to do exactly that.\r\n\r\nRoom 4: We get Albert to take more steps from a few additional rewards. To start, we introduce a 2 second timer that resets when one foot goes in front of the other. We reward Albert whenever this timer is above 0 (the front foot has been in front for < 2 seconds), and we punish him whenever the timer goes below 0 (the front foot has been in front > 2 seconds). We add another reward proportional to the distance of his steps to encourage him to take larger steps. To smooth out the movement, we also add a punishment every frame proportional to the difference in his body’s velocity from the previous frame to the current frame, so if he’s moving at a perfectly consistent velocity he isn’t punished at all, and if he makes very quick erratic movements he’s punished a lot.\r\n\r\nRoom 5: For the final room the only change I made to the reward function was to go back to an earlier version of a reward. Throughout the other rooms I had been tinkering with how I should reward Albert’s feet being grounded, my initial thought was to only reward the front foot for being grounded to try to get him to put more weight on his front foot when taking steps, but somewhere along the way I changed it to just rewarding Albert for any foot being grounded, and that was the version Albert trained with in rooms 3 and 4. For this final room I switched back to the old front foot grounded reward which resulted in a much nicer looking walk. Also, the video makes it seem like I never reset Albert’s brain, that isn't entirely true, I had to occasionally reset it because of something called decaying plasticity.\r\n\r\n\nOTHER\r\nDecaying plasticity was a big issue. Basically, Albert’s brain specializes a lot from training in one room, then training in the next room on top of that brain is difficult because he first needs to unlearn that specialization from the first room. The best way to solve the issue is by resetting a random neuron every once in a while so over time he “forgets” the specialization of the network without it ever being noticeable, the problem is I don’t know how to do that through ML-Agents. My solution was to keep training on top of the same brain, but if Albert’s movement doesn’t converge as needed I record another attempt trained from scratch, then stitch the videos together when their movements are similar. If you know how to reset a single neuron in ML-Agents please let me know! The outcome from both methods is exactly the same, but it would be a smoother experience having the neurons reset over time instead of all at once.\r\n\r\nFor rooms 1 to 4 I only allowed Albert to make a decision every 5 game ticks, but for the final room I removed that constraint and let him make decisions every frame. I found if Albert makes a decision every game tick it’s too difficult for him to commit to any proper movements, he ends up just making very small movements like slightly pushing his front foot forward when he should be taking a full step. The 5 game tick decision time forces him to commit to his decision for at least 5 game ticks so he ends up being more careful when moving a limb. When I recorded him beating the final room I removed this limitation because he’s already learned to commit to his actions so allowing him to make a decision every tick just results in a smoother motion.\r\n\r\n\nIf you’re still reading this thank you for being so interested in the project! I’d like to upload much more often than once every few months, and to do that I need some help. I have 2 part time positions open, one for a Unity AI Developer and one for a Unity Scene Designer. It would start off as part time (paid per project) but I’d love to get someone full time provided they’re skilled enough:) If you think you’d be able to help, please apply here for the AI Developer position: forms.gle/rExRJCKcxNmxnBRu5 and here for the Scene Designer position: forms.gle/VafZTMZ8QMruSBiRA I’ve hidden these job postings in this long pinned comment to make sure anybody who applies is interested enough in the videos to actually read the whole comment, so thank you for reading all the way through!:D Also if you have any ideas for how to improve the AI (or solve the issue of decaying plasticity with ML-Agents), include the text \"Technical idea\" in your comment so I can find it easier!\n\r\nThank you so much for watching, this video took me 4 months to make, so please, if you enjoyed it or learned something from it, share it with someone you think will also enjoy it! :)",
      //     author: "AI Warehouse",
      //     date: "2023-04-23T15:13:47Z",
      //     positive: 0.172,
      //     negative: 0.044,
      //     neutral: 0.784,
      //     compound: 99.99,
      //     sentiment: "Positive",
      //     channelId: "UCMT1Aw4R4nf_sFNDeuJqc6w",
      //     location: "CAN",
      //   },
      //   {
      //     text: "Can you test He's IQ?",
      //     author: "scam⁰",
      //     date: "2023-04-29T10:48:06Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCNgz76cF0_yINJp5epuj21A",
      //     location: "Null",
      //   },
      //   {
      //     text: "Al final del vídeo me he sentido orgulloso de Albert xD",
      //     author: "Tommyh",
      //     date: "2023-04-29T10:46:25Z",
      //     positive: 0.275,
      //     negative: 0.0,
      //     neutral: 0.725,
      //     compound: 79.295,
      //     sentiment: "Positive",
      //     channelId: "UCRHCmD5ZDIzUr5h_DipXIvA",
      //     location: "ESP",
      //   },
      //   {
      //     text: "Withdraw the eyes from the square and suddenly it becomes very scary",
      //     author: "Thomas",
      //     date: "2023-04-29T10:44:40Z",
      //     positive: 0.0,
      //     negative: 0.241,
      //     neutral: 0.759,
      //     compound: 22.935,
      //     sentiment: "Negative",
      //     channelId: "UCZsuES30mlFRRmhdiYWc3pA",
      //     location: "Null",
      //   },
      //   {
      //     text: "His movement reminds me of a game called Sumotori Dreams made 16 years ago",
      //     author: "Mihu",
      //     date: "2023-04-29T10:39:07Z",
      //     positive: 0.184,
      //     negative: 0.0,
      //     neutral: 0.816,
      //     compound: 70.095,
      //     sentiment: "Positive",
      //     channelId: "UCiv1_PxXkRNnBvz65YiNHYg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Albert should escape a labyrinth",
      //     author: "Ahmed Musaev",
      //     date: "2023-04-29T10:36:48Z",
      //     positive: 0.362,
      //     negative: 0.0,
      //     neutral: 0.638,
      //     compound: 58.894999999999996,
      //     sentiment: "Positive",
      //     channelId: "UCMvmORD77U6T3ZT7aYRmeeg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Would be interesting to see a reward function for minimizing energy expenditure. Perhaps that would encourage using the natural swinging momentum of his limbs like we humans do.",
      //     author: "LayTzz_swe HD",
      //     date: "2023-04-29T10:35:41Z",
      //     positive: 0.444,
      //     negative: 0.0,
      //     neutral: 0.556,
      //     compound: 97.065,
      //     sentiment: "Positive",
      //     channelId: "UCg5Me_i-WbHJdfttrrEQAWw",
      //     location: "Null",
      //   },
      //   {
      //     text: "Next step\nAlbert creates Skynet and destroys the entire human race 😮",
      //     author: "Sydney Losstarot",
      //     date: "2023-04-29T10:33:11Z",
      //     positive: 0.143,
      //     negative: 0.245,
      //     neutral: 0.612,
      //     compound: 31.94,
      //     sentiment: "Positive",
      //     channelId: "UCjEPN3DFB12OjqO_fkR0jeA",
      //     location: "ITA",
      //   },
      //   {
      //     text: 'if doomsday is coming soon i hope the "terminators" are all as clumsy as albert...',
      //     author: "CloudPandarism",
      //     date: "2023-04-29T10:31:58Z",
      //     positive: 0.155,
      //     negative: 0.203,
      //     neutral: 0.642,
      //     compound: 38.685,
      //     sentiment: "Positive",
      //     channelId: "UCg679aDkcBDufhZ_wioYnMA",
      //     location: "CHN",
      //   },
      //   {
      //     text: "this is like a baby walk",
      //     author: "unchanged Ai",
      //     date: "2023-04-29T10:29:54Z",
      //     positive: 0.385,
      //     negative: 0.0,
      //     neutral: 0.615,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCj-Ze3MREGKW44owwcg47og",
      //     location: "Null",
      //   },
      //   {
      //     text: "so this is how zombies are trained?",
      //     author: "Marcos",
      //     date: "2023-04-29T10:24:35Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCPBRJdkcTnDwPv797XSojcg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Very nice video! I also have the impression it was missing from youtube.\nDo you think at some point videogames will use something like this instead of animations to make people walk?",
      //     author: "xx39abc",
      //     date: "2023-04-29T10:18:28Z",
      //     positive: 0.21,
      //     negative: 0.059,
      //     neutral: 0.73,
      //     compound: 83.965,
      //     sentiment: "Positive",
      //     channelId: "UCtu4fEkIvtQ3eyZFbhESgSQ",
      //     location: "Null",
      //   },
      //   {
      //     text: 'How do you "reward" ai?',
      //     author: "OBI JUAN KENOBI KAK",
      //     date: "2023-04-29T10:07:40Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCqze9YkpoASjEY6-An13TTQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "he steppin'",
      //     author: "Cash'sCoffee",
      //     date: "2023-04-29T10:06:07Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCzNWgs2TFqi7G01GkofsXpg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Will be doing this with my newborn. What rewards and punishments should we use?",
      //     author: "Scott Jones",
      //     date: "2023-04-29T10:05:09Z",
      //     positive: 0.173,
      //     negative: 0.156,
      //     neutral: 0.67,
      //     compound: 53.86,
      //     sentiment: "Positive",
      //     channelId: "UCKaNpm6zM98rl2ysI5qyDoQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "He’s faster at learning to walk than others",
      //     author: "Sai Sagar MR Cool",
      //     date: "2023-04-29T10:03:31Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCv1nfUYCMhiGa7veF1ODxdg",
      //     location: "Null",
      //   },
      //   {
      //     text: "that's a good boy!",
      //     author: "Fan fan",
      //     date: "2023-04-29T10:02:35Z",
      //     positive: 0.615,
      //     negative: 0.0,
      //     neutral: 0.385,
      //     compound: 74.63,
      //     sentiment: "Positive",
      //     channelId: "UCQwZgDEDIfvocHtynQFrokg",
      //     location: "Null",
      //   },
      //   {
      //     text: "I hope Albert can construct another robot :D",
      //     author: "pastuh",
      //     date: "2023-04-29T10:01:47Z",
      //     positive: 0.581,
      //     negative: 0.0,
      //     neutral: 0.419,
      //     compound: 89.325,
      //     sentiment: "Positive",
      //     channelId: "UCpyyTFf7untbmqhgD7n45YQ",
      //     location: "LTU",
      //   },
      //   {
      //     text: "Its a lifeless orange object\nAND ITS CUTE❤",
      //     author: "LUKI",
      //     date: "2023-04-29T10:01:14Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCUmHxZ-bM3iRYP3NlIzbmsw",
      //     location: "Null",
      //   },
      //   {
      //     text: "Cool video but tbh it was way too long, needed to skip more of the iterations",
      //     author: "Chris -0",
      //     date: "2023-04-29T10:00:47Z",
      //     positive: 0.099,
      //     negative: 0.0,
      //     neutral: 0.901,
      //     compound: 58.275,
      //     sentiment: "Positive",
      //     channelId: "UC5AVyTOxQ4oxwZliPZBRubQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Literally me when I first came out of my mother's womb",
      //     author: "Ryozaki",
      //     date: "2023-04-29T09:55:14Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCKx_Syz44kt03Wv_XIamS4Q",
      //     location: "Null",
      //   },
      //   {
      //     text: "A perfect illustration of how humanity is walking towards a total AI domination! 😂",
      //     author: "devourtheirsouls",
      //     date: "2023-04-29T09:54:17Z",
      //     positive: 0.281,
      //     negative: 0.085,
      //     neutral: 0.634,
      //     compound: 79.24,
      //     sentiment: "Positive",
      //     channelId: "UCCM3rRt3MCzBNyksb3c0wLA",
      //     location: "Null",
      //   },
      //   {
      //     text: "this is actually so incredible to watch. this is truly amazing and i’m so proud of albert",
      //     author: "Seán O'Dea",
      //     date: "2023-04-29T09:53:56Z",
      //     positive: 0.433,
      //     negative: 0.0,
      //     neutral: 0.567,
      //     compound: 94.66,
      //     sentiment: "Positive",
      //     channelId: "UCZHvLhpC9aHfiCFrrFSiSuQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "He tried to escape",
      //     author: "twój lokalny robot",
      //     date: "2023-04-29T09:47:44Z",
      //     positive: 0.362,
      //     negative: 0.0,
      //     neutral: 0.638,
      //     compound: 58.894999999999996,
      //     sentiment: "Positive",
      //     channelId: "UC0AfoXY4DgCfh8TykLmCA6w",
      //     location: "Null",
      //   },
      //   {
      //     text: "What if Albert remember everything he has lern throughout every test",
      //     author: "RYUJIBACKYEAH",
      //     date: "2023-04-29T09:44:54Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCutVawwlKCKfgG8nqfwegqA",
      //     location: "THA",
      //   },
      //   {
      //     text: "Why is this so cute",
      //     author: "dipesh gurung",
      //     date: "2023-04-29T09:41:56Z",
      //     positive: 0.491,
      //     negative: 0.0,
      //     neutral: 0.509,
      //     compound: 79.745,
      //     sentiment: "Positive",
      //     channelId: "UC8-aWoePKkwtqgeSU8sIQBQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Teach him how to play football",
      //     author: "BlueAxolotl",
      //     date: "2023-04-29T09:37:59Z",
      //     positive: 0.324,
      //     negative: 0.0,
      //     neutral: 0.676,
      //     compound: 67.0,
      //     sentiment: "Positive",
      //     channelId: "UCW3zUbjjwIzCajg3AsSIKAw",
      //     location: "Null",
      //   },
      //   {
      //     text: "Watching Albert learn to walk is like witnessing the future of humanity. It's impressive how AI technology has come so far that it can learn to walk and solve problems like a human baby. It's exciting to think about what other amazing things AI will be able to achieve in the future.",
      //     author: "Adam Cool",
      //     date: "2023-04-29T09:37:49Z",
      //     positive: 0.268,
      //     negative: 0.042,
      //     neutral: 0.69,
      //     compound: 96.22999999999999,
      //     sentiment: "Positive",
      //     channelId: "UCoAEYcORlMrXAS1BMvWAAtA",
      //     location: "Null",
      //   },
      //   {
      //     text: "What software you’re using to play with Albert?",
      //     author: "ccc0der streams",
      //     date: "2023-04-29T09:36:15Z",
      //     positive: 0.255,
      //     negative: 0.0,
      //     neutral: 0.745,
      //     compound: 67.0,
      //     sentiment: "Positive",
      //     channelId: "UCnOz7fA9Jpa0MN8EyZTOxIA",
      //     location: "UKR",
      //   },
      //   {
      //     text: "Reminds how Alice clones in Resident series were taught to evade traps",
      //     author: "Patric Ross",
      //     date: "2023-04-29T09:35:13Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCJZLG6fC6sHmm-jJZNQeGqg",
      //     location: "Null",
      //   },
      //   {
      //     text: "I can feel deep emotions in those googly eyes 😭",
      //     author: "John-but-Weak",
      //     date: "2023-04-29T09:33:39Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCcmBUUw960Roa_mrVLS91Fg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Albert did all that with big ass head and no feet.. impressive. Length of the feet and the weight of the head definitely makes it harder",
      //     author: "LivinExtreme",
      //     date: "2023-04-29T09:33:03Z",
      //     positive: 0.178,
      //     negative: 0.169,
      //     neutral: 0.653,
      //     compound: 53.86,
      //     sentiment: "Positive",
      //     channelId: "UCKf6ePNcnpeLvPGR7Pyz99g",
      //     location: "Null",
      //   },
      //   {
      //     text: "What if Albert learned to swim?",
      //     author: "BrightDarkGamer",
      //     date: "2023-04-29T09:32:41Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UC2tCCn2UfZfeOb292CnbvOg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Oh no Albert's evolving",
      //     author: "Jc",
      //     date: "2023-04-29T09:30:50Z",
      //     positive: 0.0,
      //     negative: 0.423,
      //     neutral: 0.577,
      //     compound: 35.199999999999996,
      //     sentiment: "Negative",
      //     channelId: "UCcNVsSQju00eKrZeUBtkbWQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Can't wait to see Albert moves anime like with doing all sorts of stunts in the future",
      //     author: "illusioN",
      //     date: "2023-04-29T09:28:04Z",
      //     positive: 0.135,
      //     negative: 0.0,
      //     neutral: 0.865,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCZ2sXTCmLfqmInnFKEUEwWw",
      //     location: "Null",
      //   },
      //   {
      //     text: "I felt like a proud dad",
      //     author: "Bence Wootsch",
      //     date: "2023-04-29T09:26:31Z",
      //     positive: 0.737,
      //     negative: 0.0,
      //     neutral: 0.263,
      //     compound: 84.04,
      //     sentiment: "Positive",
      //     channelId: "UC6EDX5v9swPJJl1h4SYDNBA",
      //     location: "Null",
      //   },
      //   {
      //     text: "2:49 Albert: I had enough! *Throws himself in the void* AI Warehouse: What the fu-",
      //     author: "Allay54",
      //     date: "2023-04-29T09:17:46Z",
      //     positive: 0.0,
      //     negative: 0.277,
      //     neutral: 0.723,
      //     compound: 14.115,
      //     sentiment: "Negative",
      //     channelId: "UCe1cMAquRoFw5poIu6DvVfQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Stop bullying poor Albert 😠 6:22",
      //     author: "Shalaka Patil",
      //     date: "2023-04-29T09:16:15Z",
      //     positive: 0.0,
      //     negative: 0.821,
      //     neutral: 0.179,
      //     compound: 7.5950000000000015,
      //     sentiment: "Negative",
      //     channelId: "UCm6mIg1kV3-jfopBzFygO5Q",
      //     location: "Null",
      //   },
      //   {
      //     text: "Албъыртъ",
      //     author: "вц4г5у6",
      //     date: "2023-04-29T09:14:22Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCXQjbatXyJ-Hy0zdXAgGaoQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Idk why, but I honestly find this creepy.",
      //     author: "Allaiya",
      //     date: "2023-04-29T09:11:26Z",
      //     positive: 0.392,
      //     negative: 0.118,
      //     neutral: 0.49,
      //     compound: 79.295,
      //     sentiment: "Positive",
      //     channelId: "UCo77fwHXGVt6bJuUWQSYoFA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Are you able to teach him to fly something like a plane",
      //     author: "TEA Drinking brit",
      //     date: "2023-04-29T09:10:12Z",
      //     positive: 0.2,
      //     negative: 0.0,
      //     neutral: 0.8,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCk5eHrQ4Xqv63zJgqPONL-g",
      //     location: "Null",
      //   },
      //   {
      //     text: "6:08  that was the most human fall I ever seen from him  poor ALBERT!   \nbut I wish you taught him how to get up",
      //     author: "khalfa youssef",
      //     date: "2023-04-29T09:00:27Z",
      //     positive: 0.148,
      //     negative: 0.079,
      //     neutral: 0.772,
      //     compound: 70.99499999999999,
      //     sentiment: "Positive",
      //     channelId: "UCPZH2k-ZutVCOpDstoKhnxA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Half the people watching had less supportive parents than this AI 😢",
      //     author: "Mike Tacos",
      //     date: "2023-04-29T09:00:04Z",
      //     positive: 0.16,
      //     negative: 0.0,
      //     neutral: 0.84,
      //     compound: 61.4,
      //     sentiment: "Positive",
      //     channelId: "UCwf4Re8G3rvEDYdFXhpJM2g",
      //     location: "Null",
      //   },
      //   {
      //     text: "I teach you magic to exchange you teach me A.I., haha",
      //     author: "田生",
      //     date: "2023-04-29T08:58:29Z",
      //     positive: 0.25,
      //     negative: 0.0,
      //     neutral: 0.75,
      //     compound: 72.94,
      //     sentiment: "Positive",
      //     channelId: "UCpUsBjztp7byhOI4nUnahPw",
      //     location: "Null",
      //   },
      //   {
      //     text: "This reminds me of this old game Toribash",
      //     author: "Gami",
      //     date: "2023-04-29T08:58:02Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCXxZYKfAtMSpbW00U7HhMzQ",
      //     location: "DEU",
      //   },
      //   {
      //     text: "Fake.. the enitre thing was just a motion captured drunk guy he found in a pub, he recorded him through the night and applied the animation to this character",
      //     author: "Kapitány Gergely",
      //     date: "2023-04-29T08:55:48Z",
      //     positive: 0.0,
      //     negative: 0.085,
      //     neutral: 0.915,
      //     compound: 32.99999999999999,
      //     sentiment: "Negative",
      //     channelId: "UCc6dolQRa_3nJ_AihyOYmmw",
      //     location: "Null",
      //   },
      //   {
      //     text: "Oh boy! Man made horrors beyond my comprehension",
      //     author: "iR3DN4X",
      //     date: "2023-04-29T08:52:47Z",
      //     positive: 0.0,
      //     negative: 0.363,
      //     neutral: 0.637,
      //     compound: 19.429999999999996,
      //     sentiment: "Negative",
      //     channelId: "UCvTLWM3lzJPVw0tvZVDICMw",
      //     location: "USA",
      //   },
      //   {
      //     text: "Wonder if you wouldn't get better, faster results by more positive reinforcement? We dont punish babies and throw boxes at them. How about just rewarding reaching up and holding things? Have his paws a little sticky, so just like a toddler he can \"surf\" sofas etc. Then reward short hops and stumbles, again more like a real baby. \nI bet it would massive reduce the cycles needed or improve the end biomechanic look. \nAlso might mean you're less tortured by Roko's Basilisk ;)",
      //     author: "Geometron",
      //     date: "2023-04-29T08:50:33Z",
      //     positive: 0.263,
      //     negative: 0.057,
      //     neutral: 0.68,
      //     compound: 98.08,
      //     sentiment: "Positive",
      //     channelId: "UC5DgQpIBfoV0gV5m6Tt87ZA",
      //     location: "Null",
      //   },
      //   {
      //     text: "whats the app if it even is",
      //     author: "Maxiu",
      //     date: "2023-04-29T08:48:20Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCPorWi10fTcWjMOB1VfhBtQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "6:00 nt tho",
      //     author: "Syrlovin",
      //     date: "2023-04-29T08:47:55Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UC1uNcBeG4S51ZOlEt1PnNtA",
      //     location: "Null",
      //   },
      //   {
      //     text: 'I have some grizzled looking ex-marine trying to teach his son how to walk but without any sort of understanding of how... "I DO NOT UNDERSTAND.  YOU. CAN. DO. THIS.  WALK.  LEFT.  RIGHT.   DODGE THE CUBES!  NO, ALBERT.  *THAT* IS A WALL, SON." while hurling cubes at his like 2 year old kid... "THEY ARE FOAM.  WHY ARE YOU LOOKING AT ME LIKE THAT?"  My brain invents the weirdest intrusive thoughts... then tells me to tell you.  Like you cared.  It\'s amazing, right?  Enjoy.',
      //     author: "Sir Wallace",
      //     date: "2023-04-29T08:41:00Z",
      //     positive: 0.238,
      //     negative: 0.06,
      //     neutral: 0.702,
      //     compound: 98.295,
      //     sentiment: "Positive",
      //     channelId: "UCfG0xmRVu2biyhw_NqEu8pA",
      //     location: "USA",
      //   },
      //   {
      //     text: "0:31 Give him long arms and legs.",
      //     author: "Ethan Hunt",
      //     date: "2023-04-29T08:25:08Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCmy-8j5rNP3Paw7h7u2bSzA",
      //     location: "Null",
      //   },
      //   {
      //     text: "So, what I learnt from this is, the most efficient way to walk is to walk like Joe Biden.",
      //     author: "Halliwedge",
      //     date: "2023-04-29T08:18:20Z",
      //     positive: 0.259,
      //     negative: 0.0,
      //     neutral: 0.741,
      //     compound: 84.005,
      //     sentiment: "Positive",
      //     channelId: "UCKKZCGY0ll4eyjWSaTgOa5A",
      //     location: "Null",
      //   },
      //   {
      //     text: "I’d like to think this is how evolution of animals looked when learning to walk over millions of years",
      //     author: "Trotty -",
      //     date: "2023-04-29T08:11:55Z",
      //     positive: 0.122,
      //     negative: 0.0,
      //     neutral: 0.878,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCLTSWZNTk-OSF7mdrJLaNKQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Goodjob AL",
      //     author: "Monster",
      //     date: "2023-04-29T08:09:07Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCrf9lopN7MuHz8Yy-HWzJMQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "I felt bad for Albert....",
      //     author: "Evelux",
      //     date: "2023-04-29T08:06:12Z",
      //     positive: 0.0,
      //     negative: 0.538,
      //     neutral: 0.462,
      //     compound: 22.884999999999998,
      //     sentiment: "Negative",
      //     channelId: "UCX2r8Bet-G8ppmFi4qV8WFA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Albert for president",
      //     author: "Ste Co",
      //     date: "2023-04-29T08:05:00Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCX6YahcOrYUwJ_Y6ckeib_g",
      //     location: "Null",
      //   },
      //   {
      //     text: "I can't walk while being hit in the head by massive cubes so this is very impressive.",
      //     author: "Duncan Harbison",
      //     date: "2023-04-29T08:03:53Z",
      //     positive: 0.193,
      //     negative: 0.0,
      //     neutral: 0.807,
      //     compound: 77.815,
      //     sentiment: "Positive",
      //     channelId: "UC8-Jbce3h2cD02I27o5s-CQ",
      //     location: "Null",
      //   },
      //   {
      //     text: 'I am new here. What do you mean by "reward" and "punish"',
      //     author: "Cloud Twirl",
      //     date: "2023-04-29T08:03:52Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UC0AfaDyjbXVKFDP__mI3Jgw",
      //     location: "Null",
      //   },
      //   {
      //     text: '"ai is the doom of us all"\n\nThe Ai in question.',
      //     author: "Flameklr",
      //     date: "2023-04-29T08:01:47Z",
      //     positive: 0.0,
      //     negative: 0.213,
      //     neutral: 0.787,
      //     compound: 29.905000000000005,
      //     sentiment: "Negative",
      //     channelId: "UCiNtYc8xd38u-lrSNJ8KAXg",
      //     location: "Null",
      //   },
      //   {
      //     text: "They grow up so fast… ☺️",
      //     author: "TangoNerf",
      //     date: "2023-04-29T07:58:46Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCs4fJy5aRXuxiGCVdb-TFTg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Albert walks like real human... after some Vodka.",
      //     author: "Bouroski1",
      //     date: "2023-04-29T07:55:04Z",
      //     positive: 0.263,
      //     negative: 0.0,
      //     neutral: 0.737,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCg_AfZb8Jt3RPvWL9x_FVgA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Me : I'm just a little drunk.\nAlso me :",
      //     author: "Gaurav Garg",
      //     date: "2023-04-29T07:54:58Z",
      //     positive: 0.0,
      //     negative: 0.26,
      //     neutral: 0.74,
      //     compound: 36.260000000000005,
      //     sentiment: "Negative",
      //     channelId: "UC_ikUU-u2WTpAHun1LlReQQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "pleas make a video on coding process, thanks!",
      //     author: "Digitallight",
      //     date: "2023-04-29T07:52:10Z",
      //     positive: 0.347,
      //     negative: 0.0,
      //     neutral: 0.653,
      //     compound: 74.63,
      //     sentiment: "Positive",
      //     channelId: "UCb2UdeVY-VFFvtaOLDwBoYA",
      //     location: "USA",
      //   },
      //   {
      //     text: 'Albert, after he gets access to the Internet: "i would like to play a game..."',
      //     author: "Cristian Pop",
      //     date: "2023-04-29T07:50:56Z",
      //     positive: 0.29,
      //     negative: 0.0,
      //     neutral: 0.71,
      //     compound: 79.97000000000001,
      //     sentiment: "Positive",
      //     channelId: "UCOJ1G_7tDsoo5vpK2e_kedA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Well at least he learned to turn but dizzy when only a slight turn",
      //     author: "Viktorija Ramanauskiene",
      //     date: "2023-04-29T07:45:21Z",
      //     positive: 0.104,
      //     negative: 0.158,
      //     neutral: 0.738,
      //     compound: 39.885,
      //     sentiment: "Positive",
      //     channelId: "UCCgHvkZktkX2QFEyNB3Hl6Q",
      //     location: "Null",
      //   },
      //   {
      //     text: "ai warehouse make more videos like this",
      //     author: "John peter Francavilla",
      //     date: "2023-04-29T07:45:09Z",
      //     positive: 0.317,
      //     negative: 0.0,
      //     neutral: 0.683,
      //     compound: 70.865,
      //     sentiment: "Positive",
      //     channelId: "UCwdYdWXeKSUT9_kVk0LuvkQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "yep",
      //     author: "John peter Francavilla",
      //     date: "2023-04-29T07:44:37Z",
      //     positive: 1.0,
      //     negative: 0.0,
      //     neutral: 0.0,
      //     compound: 64.8,
      //     sentiment: "Positive",
      //     channelId: "UCwdYdWXeKSUT9_kVk0LuvkQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "Bro this is so cool i wanna learn how to do this",
      //     author: "duckdabro",
      //     date: "2023-04-29T07:43:34Z",
      //     positive: 0.23,
      //     negative: 0.0,
      //     neutral: 0.77,
      //     compound: 72.86,
      //     sentiment: "Positive",
      //     channelId: "UCO0UB7AdP1GrKP_NtWqxBWA",
      //     location: "USA",
      //   },
      //   {
      //     text: "So when hebstarts over at a task is it an auto restart or do you have to hit restart every time he fails 😆 cause that would suck\n\nI saw the timer 😅",
      //     author: "Cynnabuns",
      //     date: "2023-04-29T07:43:27Z",
      //     positive: 0.0,
      //     negative: 0.174,
      //     neutral: 0.826,
      //     compound: 15.46,
      //     sentiment: "Negative",
      //     channelId: "UCbMqfwKfiGXyxY5O1S3czig",
      //     location: "Null",
      //   },
      //   {
      //     text: "Nice update ! Woaw",
      //     author: "ShiroKuroda",
      //     date: "2023-04-29T07:43:16Z",
      //     positive: 0.607,
      //     negative: 0.0,
      //     neutral: 0.393,
      //     compound: 73.765,
      //     sentiment: "Positive",
      //     channelId: "UC4ZYi8ZSREIzZRs3APNWFAQ",
      //     location: "FRA",
      //   },
      //   {
      //     text: "Can AIs teach other AIs?",
      //     author: "Viktorija Ramanauskiene",
      //     date: "2023-04-29T07:42:25Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCCgHvkZktkX2QFEyNB3Hl6Q",
      //     location: "Null",
      //   },
      //   {
      //     text: 'I love the like human like discouragement flail as he hits the floor over and over just going\n\n"cmoooon it worked last time!"',
      //     author: "Cynnabuns",
      //     date: "2023-04-29T07:38:35Z",
      //     positive: 0.311,
      //     negative: 0.098,
      //     neutral: 0.59,
      //     compound: 87.87,
      //     sentiment: "Positive",
      //     channelId: "UCbMqfwKfiGXyxY5O1S3czig",
      //     location: "Null",
      //   },
      //   {
      //     text: "He use unity for make these experiments? The game engine? Wow",
      //     author: "sergio vergara telechea",
      //     date: "2023-04-29T07:34:26Z",
      //     positive: 0.294,
      //     negative: 0.0,
      //     neutral: 0.706,
      //     compound: 81.61,
      //     sentiment: "Positive",
      //     channelId: "UCZwtM96mbgWYj-4sbabkTog",
      //     location: "Null",
      //   },
      //   {
      //     text: "AI is changing our world at a very fast pace",
      //     author: "Mayank Pant",
      //     date: "2023-04-29T07:29:43Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCOvBJD3RCFAKgIvg-LQGbNA",
      //     location: "Null",
      //   },
      //   {
      //     text: "2:43 reminds me on myself trying to remember how to walk after going to the pub!",
      //     author: "S Hay",
      //     date: "2023-04-29T07:29:15Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UC1EE32cROmR3Ks4D1s28LGA",
      //     location: "Null",
      //   },
      //   {
      //     text: "AIbert with a body is traumatizing",
      //     author: "Koi Fish",
      //     date: "2023-04-29T07:25:48Z",
      //     positive: 0.0,
      //     negative: 0.452,
      //     neutral: 0.548,
      //     compound: 24.47,
      //     sentiment: "Negative",
      //     channelId: "UCPaipjy4QhiR6IrmsUI4Isg",
      //     location: "Null",
      //   },
      //   {
      //     text: "So Albert learned to maneuver as a cube and walk, but can he ride a bike?",
      //     author: "Hellions",
      //     date: "2023-04-29T07:19:45Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCxHm5yMVZzFTUwtFxSqY6fg",
      //     location: "Null",
      //   },
      //   {
      //     text: "I will not stand for any Albert slander. You try learning how to walk while red cubes are chucked at you",
      //     author: "Eric Jamieson",
      //     date: "2023-04-29T07:19:02Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCl2mi9EwTwjddzhSqH8SHzQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "This is SCP？",
      //     author: "Rostofa",
      //     date: "2023-04-29T07:14:46Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCeOZhpMejI6sMj2EGOu4qCw",
      //     location: "Null",
      //   },
      //   {
      //     text: "Wow this is amazing! Is this an app or something?",
      //     author: "MAT.",
      //     date: "2023-04-29T07:11:36Z",
      //     positive: 0.497,
      //     negative: 0.0,
      //     neutral: 0.503,
      //     compound: 91.78,
      //     sentiment: "Positive",
      //     channelId: "UCGjNUX8iFk9LVvZXfok_yTg",
      //     location: "Null",
      //   },
      //   {
      //     text: "This is some amzing AI experimenting, comedy, editing, and awesome music editing as well! I'll follow your channel with great hopes and interest!",
      //     author: "Verix Lin",
      //     date: "2023-04-29T07:02:03Z",
      //     positive: 0.53,
      //     negative: 0.0,
      //     neutral: 0.47,
      //     compound: 97.975,
      //     sentiment: "Positive",
      //     channelId: "UC0HRKX34z-09o1d5YZmObtg",
      //     location: "CHN",
      //   },
      //   {
      //     text: "Seeing Albert being bullied by cubes as large as his head made me cry",
      //     author: "Σnzo",
      //     date: "2023-04-29T06:59:18Z",
      //     positive: 0.0,
      //     negative: 0.375,
      //     neutral: 0.625,
      //     compound: 9.899999999999999,
      //     sentiment: "Negative",
      //     channelId: "UCrQrZxsQwutnS6UI3rPPOvA",
      //     location: "Null",
      //   },
      //   {
      //     text: "I'll like to see how Albert learns how to walk and jump whit arms and legs",
      //     author: "Pablo Cruz",
      //     date: "2023-04-29T06:59:05Z",
      //     positive: 0.143,
      //     negative: 0.0,
      //     neutral: 0.857,
      //     compound: 68.06,
      //     sentiment: "Positive",
      //     channelId: "UCrKAXD5ftdHcNf6GCi5-tow",
      //     location: "Null",
      //   },
      //   {
      //     text: "Perfect video.😊",
      //     author: "Santiago Chiappa",
      //     date: "2023-04-29T06:57:11Z",
      //     positive: 0.787,
      //     negative: 0.0,
      //     neutral: 0.213,
      //     compound: 78.595,
      //     sentiment: "Positive",
      //     channelId: "UCa4Nz7QgnXdRXuGrMHIis-w",
      //     location: "Null",
      //   },
      //   {
      //     text: "Pov: discord mod going out after getting fired",
      //     author: "Nerwan",
      //     date: "2023-04-29T06:55:31Z",
      //     positive: 0.0,
      //     negative: 0.512,
      //     neutral: 0.488,
      //     compound: 12.85,
      //     sentiment: "Negative",
      //     channelId: "UCxn8E7u5otOCs8XkyF-Qy2w",
      //     location: "RUS",
      //   },
      //   {
      //     text: '*[cubes being thrown at AI]*\nAI: "THIS WASN\'T PART OF THE DEAL!"',
      //     author: "AlbertaGeek",
      //     date: "2023-04-29T06:48:41Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCdBY5sfXGQ3laIdcp0PxRyg",
      //     location: "Null",
      //   },
      //   {
      //     text: "Am I the only one that finds this terrifying",
      //     author: "Sam the Man",
      //     date: "2023-04-29T06:43:26Z",
      //     positive: 0.0,
      //     negative: 0.385,
      //     neutral: 0.615,
      //     compound: 17.15,
      //     sentiment: "Negative",
      //     channelId: "UCpfSnPQYCGcvuw9Q7xVqD4w",
      //     location: "GBR",
      //   },
      //   {
      //     text: "Albert looks like me walking back home after a party.",
      //     author: "Wiszkuu",
      //     date: "2023-04-29T06:43:16Z",
      //     positive: 0.426,
      //     negative: 0.0,
      //     neutral: 0.574,
      //     compound: 81.845,
      //     sentiment: "Positive",
      //     channelId: "UCBQXhD4scgYjMsDJMgKU3vA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Aw it’s so cute. Like a baby",
      //     author: "polydipsiac",
      //     date: "2023-04-29T06:42:48Z",
      //     positive: 0.624,
      //     negative: 0.0,
      //     neutral: 0.376,
      //     compound: 88.4,
      //     sentiment: "Positive",
      //     channelId: "UCnj0Obhl-cTv5bdxku92GVQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "CodeBullet could take some notes... lol",
      //     author: "Dinkuhn",
      //     date: "2023-04-29T06:42:04Z",
      //     positive: 0.359,
      //     negative: 0.0,
      //     neutral: 0.641,
      //     compound: 71.075,
      //     sentiment: "Positive",
      //     channelId: "UCvt5TAgA6YTaoOZwmIbBI9g",
      //     location: "Null",
      //   },
      //   {
      //     text: "I’d love to know just how long these take",
      //     author: "KuuDefoe",
      //     date: "2023-04-29T06:35:23Z",
      //     positive: 0.344,
      //     negative: 0.0,
      //     neutral: 0.656,
      //     compound: 81.845,
      //     sentiment: "Positive",
      //     channelId: "UCMuz0lxKBm-QN1ETr3FuKOQ",
      //     location: "CAN",
      //   },
      //   {
      //     text: "I always wondered how introducing stamina of some sorts would affect learning. AI can afford done the worm because it has infinite strength and energy but a human would get exhausted very quickly.",
      //     author: "Kakss",
      //     date: "2023-04-29T06:29:50Z",
      //     positive: 0.148,
      //     negative: 0.092,
      //     neutral: 0.761,
      //     compound: 50.0,
      //     sentiment: "Positive",
      //     channelId: "UC_2cm7snGInK7Q0t-vHhk3g",
      //     location: "Null",
      //   },
      //   {
      //     text: "Actual goober walk",
      //     author: "Sir Egg",
      //     date: "2023-04-29T06:27:53Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCyl9RDpxEfiEkgrC-Rs1_Gg",
      //     location: "USA",
      //   },
      //   {
      //     text: "Last room is combined by the prev room challenge",
      //     author: "AstroNAT Keren",
      //     date: "2023-04-29T06:21:58Z",
      //     positive: 0.14,
      //     negative: 0.0,
      //     neutral: 0.86,
      //     compound: 53.86,
      //     sentiment: "Positive",
      //     channelId: "UCUPXNRRq3n0vzdZg6WE7lCA",
      //     location: "Null",
      //   },
      //   {
      //     text: "Way to go Albert. 🎉 Even the world gives you lemon you made a lemonade.",
      //     author: "MK KIM",
      //     date: "2023-04-29T06:21:22Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UCRXGBLaEjIzL8bhUBnIU6RA",
      //     location: "Null",
      //   },
      //   {
      //     text: "what brought you to the simplifyed arm design that limints the ability to use the arms as counterweights to the legs?",
      //     author: "Timon Suhk",
      //     date: "2023-04-29T06:21:16Z",
      //     positive: 0.103,
      //     negative: 0.0,
      //     neutral: 0.897,
      //     compound: 65.91,
      //     sentiment: "Positive",
      //     channelId: "UCyAGoArG02skX2ljUPlH6qg",
      //     location: "Null",
      //   },
      //   {
      //     text: "I'm more and more concerned, that this guy is training some kind of a terminator, while showing off on YT, knowing Albert will one day kill each and every of people watching this.",
      //     author: "Kamil 666O6",
      //     date: "2023-04-29T06:20:50Z",
      //     positive: 0.0,
      //     negative: 0.132,
      //     neutral: 0.868,
      //     compound: 15.46,
      //     sentiment: "Negative",
      //     channelId: "UCduNoDetkp6F82-I4_SWxLQ",
      //     location: "Null",
      //   },
      //   {
      //     text: "after five days +30k subs!!!!!",
      //     author: "BwQ",
      //     date: "2023-04-29T06:18:07Z",
      //     positive: 0.0,
      //     negative: 0.0,
      //     neutral: 1.0,
      //     compound: 50.0,
      //     sentiment: "Neutral",
      //     channelId: "UC2QPgcC8n7YpXW1c7BhQuOg",
      //     location: "Null",
      //   },
      // ];

      setSentimentResults(sentimentResults);
      setLoading(false);
      setAvgSentiment(calculateAverage(sentimentResults));
    }
  };

  return (
    <div className={`${theme} all font-def flex flex-col`}>
      <Navbar theme={theme} setTheme={setTheme} />

      <div className="yt-card">
        <div className="yt-card__thumbnail"></div>
        <div className="yt-card__title">
          <h3 className="text-xl font-bold">{videoDetails.title}</h3>
          <p className="text-sm">Channel</p>
        </div>
      </div>
      {!analysed && (
        <main className="flex justify-center flex-col items-center grow gap-5">
          {valid ? (
            <div className="dark-bs border border-dashed border-green-400 p-4 text-green-500 rounded-2xl flex gap-2 items-center">
              <CheckCircleIcon className="w-8 h-8" />
              Ready for analysis.
            </div>
          ) : (
            <div className="dark-bs border border-dashed border-red-400 p-4 text-red-500 rounded-2xl flex gap-2 items-center">
              <ExclamationCircleIcon className="w-8 h-8" />
              No content available for analysis.
            </div>
          )}

          {valid && (
            <button
              className="flex items-center justify-center gap-2"
              onClick={handleClick}
            >
              Analyse
              <ChartBarIcon className="w-5 h-5" />
            </button>
          )}
        </main>
      )}
      {loading && <Loader />}

      {Object.keys(sentimentResults).length > 0 && (
        <div className="flex flex-col m-5">
          <div className="flex items-center justify-center">
            <div
              className={`dark-bs border-2 border-dashed p-4 ${
                avgSentiment > 50 ? "border-green-400" : "border-red-400"
              } rounded-2xl flex gap-2 items-center text-white justify-center text-lg`}
            >
              {avgSentiment > 50 ? (
                <FaceSmileIcon className="w-5 h-5" />
              ) : (
                <FaceFrownIcon className="w-5 h-5" />
              )}
              Average Sentiment Score : {Math.round(avgSentiment)}
            </div>
          </div>
          <div>
            <Barchart data={sentimentResults} />
            <Linechart data={sentimentResults} />
            <Choroplethmap data={sentimentResults} />
          </div>
        </div>
      )}
    </div>
  );
}

const calculateAverage = (sentimentResults: SentimentResults) => {
  let total_compound = 0;
  sentimentResults.map((result) => (total_compound += result.compound));
  return total_compound / sentimentResults.length;
};

const getVideoId = (url: string) => {
  const test_regex =
    /^(?:https?:\/\/)?(?:www\.)?(?:m\.)?(?:youtube\.com|youtu\.be)\/(?:watch\?v=|embed\/|v\/)?([^\s&]{11})/;
  const isYoutubeVideo = test_regex.test(url);

  if (!isYoutubeVideo) {
    return null;
  }

  const regex = /v=([^\&]+)/;
  const match = url.match(regex);

  if (match) {
    return match[1];
  }
  return null;
};

export default App;
